USE gfg;

-- ORDER BY ASCENDING
SELECT * FROM employees ORDER BY age ASC;

-- ORDER BY DESCENDING
SELECT * FROM employees ORDER BY age DESC;

-- FIRST ORDERS BY AGE AND THEN NAME
SELECT * FROM employees ORDER BY age DESC , name;

-- FIRST ORDEERS BY NAME AND THEN BY AGE
SELECT * FROM employees ORDER BY name DESC , age;